#!/usr/bin/bash
#PBS -l walltime=12:00:00
#PBS -l mem=36Gb
#PBS -l ncpus=9
#PBS -l select=cputype=cascadelake
#PBS -j oe
set -e

lscpu

cd "${PBS_O_WORKDIR}"

module add crest
module add orca

yes | /srv/scratch/${USER}/.censo/bin/censo --cleanup_all > censo_cleanup.out
/srv/scratch/${USER}/.censo/bin/censo -i crest_conformers.xyz --maxcores 9 -O 1 > censo.out
